version: "3"

services:
  # helferplan-frontend:
  #   build: ./frontend
  #   container_name: helferplan-frontend
  #   restart: unless-stopped
  #   networks:
  #     - helferplannetwork
  #   ports:
  #     - 4200:80
    
  helferplan-backend:
    image: strapi/strapi
    container_name: helferplan-backend
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: helferplan-db
      DATABASE_PORT: 27017
      DATABASE_CLIENT: mongo
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - helferplannetwork
    volumes:
      - ./backend:/srv/app
    ports:
      - 1337:1337

  helferplan-db:
    image: mongo
    container_name: helferplan-db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - helferplannetwork
    volumes:
      - helferplandata:/data/db

networks:
  helferplannetwork:
    driver: bridge

volumes:
  helferplandata:
